# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\qt_interface\interface_graphique.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(791, 634)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Button_Etudiant = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Etudiant.setGeometry(QtCore.QRect(84, 280, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(11)
        self.Button_Etudiant.setFont(font)
        self.Button_Etudiant.setObjectName("Button_Etudiant")
        self.Edit_nom_etudiant = QtWidgets.QLineEdit(self.centralwidget)
        self.Edit_nom_etudiant.setGeometry(QtCore.QRect(100, 150, 141, 31))
        self.Edit_nom_etudiant.setObjectName("Edit_nom_etudiant")
        self.label_affichage = QtWidgets.QLabel(self.centralwidget)
        self.label_affichage.setGeometry(QtCore.QRect(46, 432, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_affichage.setFont(font)
        self.label_affichage.setText("")
        self.label_affichage.setObjectName("label_affichage")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 791, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button_Etudiant.setText(_translate("MainWindow", "Ajouter étudiant"))
